DROP TABLE IF EXISTS `Weibo_tweet`;

CREATE TABLE `Weibo_tweet` (
  `STATUS_ID` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '本地ID',
  `ID` bigint(11) DEFAULT NULL COMMENT '对应 具体媒体类型的微博编号',
  `TEXT` text COMMENT '微博内容',
  `SOURCE` varchar(500) DEFAULT NULL COMMENT '数据 来源Eg,网页等',
  `SOURCE_URL` varchar(500) DEFAULT NULL COMMENT '来源网站地址',
  `TRUNCATED` int(11) DEFAULT '0' COMMENT '是否被截断:0:未被截断,1:已截断',
  `REPLY_STATUS_ID` bigint(11) DEFAULT NULL COMMENT '回复微博编号',
  `REPLY_USER_ID` bigint(11) DEFAULT NULL COMMENT '回复人编号',
  `REPLY_SCREEN_NAME` varchar(50) DEFAULT NULL COMMENT '回复人昵称',
  `THUMBNAIL_PIC` varchar(2000) DEFAULT NULL COMMENT '缩略图',
  `BMIDDLE_PIC` varchar(100) DEFAULT NULL COMMENT '中型图',
  `ORIGINAL_PIC` varchar(100) DEFAULT NULL COMMENT '原图',
  `USER_ID` varchar(100) DEFAULT NULL COMMENT '用户 编号',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '发帖 时间',
  `SCREEN_NAME` varchar(100) DEFAULT NULL COMMENT '用户昵称',
  `PROVINCE` int(11) DEFAULT '0' COMMENT '所属省 份',
  `CITY` int(11) DEFAULT '0' COMMENT '所属城市',
  `LOCATION` varchar(200) DEFAULT NULL COMMENT '用户地址',
  `DESCRIPTION` varchar(2000) DEFAULT NULL COMMENT '个人描述',
  `URL` varchar(200) DEFAULT NULL COMMENT '博客 地址',
  `IMAGE_URL` varchar(100) DEFAULT NULL COMMENT '用户头像',
  `DOMAIN` varchar(50) DEFAULT NULL COMMENT '用户 二级域名',
  `GENDER` int(11) DEFAULT '0' COMMENT '性别:0:未知、1:男、2:女',
  `FOLLOWS_COUNT` int(11) DEFAULT '0' COMMENT '粉丝数',
  `FRIENDS_COUNT` int(11) DEFAULT '0' COMMENT '好友数',
  `STATUS_COUNT` int(11) DEFAULT '0' COMMENT '微博数',
  `USER_CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `VERIFIED` int(8) DEFAULT '0' COMMENT '0:未 认证，对应Verify_type<0；\r\n1:个人认证，对应verify_type=0；\r\n2:未知，对应不到上面的各种类型\r\n3:企业认证， 对应verify_type>=1，且不包含达人认证\r\n4:达人认证,对应verify_type>=200 && verify_type<=300',
  `RT_ID` bigint(11) DEFAULT NULL COMMENT '原帖编号',
  `RT_TEXT` text COMMENT '原帖内容',
  `RT_SOURCE` varchar(50) DEFAULT NULL COMMENT '来源:Eg:手机客户端 sina微薄',
  `RT_SOURCE_URL` varchar(500) DEFAULT NULL,
  `RT_TRUNCATED` int(11) DEFAULT '0' COMMENT '是否被 截断:0:未被截断,1:已截断',
  `RT_REPLY_STATUS_ID` bigint(11) DEFAULT NULL COMMENT '回复微博编号',
  `RT_REPLY_USER_ID` bigint(11) DEFAULT NULL COMMENT '回复人编号',
  `RT_REPLY_SCREEN_NAME` varchar(50) DEFAULT NULL COMMENT '回复人昵称',
  `RT_THUMBNAIL_PIC` varchar(2000) DEFAULT NULL COMMENT '缩略图',
  `RT_BMIDDLE_PIC` varchar(100) DEFAULT NULL COMMENT '中型图',
  `RT_ORIGINAL_PIC` varchar(100) DEFAULT NULL COMMENT '原图',
  `RT_USER_ID` varchar(100) DEFAULT NULL COMMENT '转帖用户编号',
  `RT_CREATE_TIME` datetime DEFAULT NULL COMMENT '发帖时间',
  `RT_SCREEN_NAME` varchar(100) DEFAULT NULL COMMENT '微博昵称',
  `RT_PROVINCE` int(11) DEFAULT NULL COMMENT '所属 省份',
  `RT_CITY` int(11) DEFAULT NULL COMMENT '所属 城市',
  `RT_LOCATION` varchar(200) DEFAULT NULL COMMENT '地址',
  `RT_DESCRIPTION` varchar(2000) DEFAULT NULL COMMENT '个人描述',
  `RT_URL` varchar(200) DEFAULT NULL COMMENT '博客 地址',
  `RT_IMAGE_URL` varchar(200) DEFAULT NULL COMMENT '头像地址',
  `RT_DOMAIN` varchar(50) DEFAULT NULL COMMENT '用户二级域名',
  `RT_GENDER` int(11) unsigned zerofill DEFAULT '00000000000' COMMENT '性别:0:未知、1:男、2:女',
  `RT_FOLLOWS_COUNT` int(11) DEFAULT '0' COMMENT '粉丝数',
  `RT_FRIENDS_COUNT` int(11) DEFAULT '0' COMMENT '好友数',
  `RT_STATUS_COUNT` int(11) DEFAULT '0' COMMENT '微博数',
  `RT_USER_CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `RT_VERIFIED` int(11) DEFAULT '0' COMMENT '认证标 识,0:未认证,1:已认证',
  `RT_COUNT` int(11) DEFAULT NULL COMMENT '转帖 次数',
  `CT_COUNT` int(11) DEFAULT NULL COMMENT '评论 次数',
  `TYPE` int(11) DEFAULT '1' COMMENT '媒体类型,1:新浪',
  `FAVORITE` int(11) DEFAULT '0' COMMENT '赞数',
  PRIMARY KEY (`STATUS_ID`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=364 DEFAULT CHARSET=utf8;
